// CitizenshipApp/CitizenshipApp/app/welcome.tsx
import React, { useState } from "react";
import {
  KeyboardAvoidingView,
  Platform,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { LinearGradient } from "expo-linear-gradient";
import { router } from "expo-router";
import { useApp } from "@/context/AppContext";

const US_STATES: Array<[name: string, code: string]> = [
  ["Alabama", "AL"], ["Alaska", "AK"], ["Arizona", "AZ"], ["Arkansas", "AR"],
  ["California", "CA"], ["Colorado", "CO"], ["Connecticut", "CT"], ["Delaware", "DE"],
  ["Florida", "FL"], ["Georgia", "GA"], ["Hawaii", "HI"], ["Idaho", "ID"],
  ["Illinois", "IL"], ["Indiana", "IN"], ["Iowa", "IA"], ["Kansas", "KS"],
  ["Kentucky", "KY"], ["Louisiana", "LA"], ["Maine", "ME"], ["Maryland", "MD"],
  ["Massachusetts", "MA"], ["Michigan", "MI"], ["Minnesota", "MN"], ["Mississippi", "MS"],
  ["Missouri", "MO"], ["Montana", "MT"], ["Nebraska", "NE"], ["Nevada", "NV"],
  ["New Hampshire", "NH"], ["New Jersey", "NJ"], ["New Mexico", "NM"], ["New York", "NY"],
  ["North Carolina", "NC"], ["North Dakota", "ND"], ["Ohio", "OH"], ["Oklahoma", "OK"],
  ["Oregon", "OR"], ["Pennsylvania", "PA"], ["Rhode Island", "RI"], ["South Carolina", "SC"],
  ["South Dakota", "SD"], ["Tennessee", "TN"], ["Texas", "TX"], ["Utah", "UT"],
  ["Vermont", "VT"], ["Virginia", "VA"], ["Washington", "WA"], ["West Virginia", "WV"],
  ["Wisconsin", "WI"], ["Wyoming", "WY"],
];

export default function WelcomeScreen() {
  const { updateSettings } = useApp();
  const [firstName, setFirstName] = useState("");
  const [homeState, setHomeState] = useState("WI");

  async function getStarted() {
    const name = firstName.trim();
    await updateSettings({
      userName: name || "Future Citizen",
      homeState,
      hasOnboarded: true,
    });
    router.replace("/");
  }

  async function skip() {
    await updateSettings({ hasOnboarded: true });
    router.replace("/");
  }

  return (
    <LinearGradient colors={["#312e81", "#4338ca", "#312e81"]} style={styles.root}>
      <SafeAreaView style={styles.safe}>
        <KeyboardAvoidingView
          behavior={Platform.OS === "ios" ? "padding" : undefined}
          style={styles.flex}
        >
          <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
            <Text style={styles.flag}>🗽</Text>
            <Text style={styles.title}>Welcome to{"\n"}CitizenFlow</Text>
            <Text style={styles.subtitle}>
              Your free, ad-free path to the U.S. Citizenship Test. Let's personalize your study.
            </Text>

            <View style={styles.card}>
              <Text style={styles.label}>First name</Text>
              <TextInput
                value={firstName}
                onChangeText={setFirstName}
                placeholder="e.g. Maria"
                placeholderTextColor="#9ca3af"
                style={styles.input}
                autoCapitalize="words"
                returnKeyType="done"
              />

              <Text style={[styles.label, { marginTop: 18 }]}>Your state</Text>
              <View style={styles.chips}>
                {US_STATES.map(([name, code]) => {
                  const active = homeState === code;
                  return (
                    <TouchableOpacity
                      key={code}
                      style={[styles.chip, active && styles.chipActive]}
                      onPress={() => setHomeState(code)}
                      accessibilityLabel={name}
                    >
                      <Text style={[styles.chipText, active && styles.chipTextActive]}>{code}</Text>
                    </TouchableOpacity>
                  );
                })}
              </View>

              <TouchableOpacity style={styles.cta} onPress={getStarted} activeOpacity={0.85}>
                <Text style={styles.ctaText}>Get Started →</Text>
              </TouchableOpacity>
              <TouchableOpacity style={styles.skip} onPress={skip}>
                <Text style={styles.skipText}>Skip for now</Text>
              </TouchableOpacity>
            </View>
          </ScrollView>
        </KeyboardAvoidingView>
      </SafeAreaView>
    </LinearGradient>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1 },
  safe: { flex: 1 },
  flex: { flex: 1 },
  scroll: { padding: 24, paddingBottom: 40, flexGrow: 1, justifyContent: "center" },
  flag: { fontSize: 52, textAlign: "center", marginBottom: 8 },
  title: {
    fontSize: 30,
    fontWeight: "800",
    color: "#ffffff",
    textAlign: "center",
    lineHeight: 36,
  },
  subtitle: {
    fontSize: 15,
    color: "#c7d2fe",
    textAlign: "center",
    lineHeight: 22,
    marginTop: 12,
    marginBottom: 24,
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 22,
    padding: 22,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.3,
    shadowRadius: 24,
    elevation: 12,
  },
  label: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: "#6366f1",
    marginBottom: 8,
  },
  input: {
    borderWidth: 1.5,
    borderColor: "#e2e6f3",
    backgroundColor: "#f8f9ff",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    color: "#1a1f36",
  },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 10,
    backgroundColor: "#f1f5f9",
  },
  chipActive: { backgroundColor: "#4f46e5" },
  chipText: { fontSize: 13, fontWeight: "600", color: "#475569" },
  chipTextActive: { color: "#fff" },
  cta: {
    marginTop: 22,
    backgroundColor: "#4f46e5",
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: "center",
  },
  ctaText: { color: "#fff", fontWeight: "800", fontSize: 16 },
  skip: { marginTop: 12, alignItems: "center" },
  skipText: { color: "#9ca3af", fontWeight: "600", fontSize: 13 },
});

// Frontend/src/app/pages/welcome/welcome.component.ts
import { Component, inject, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AppStateService } from '../../services/app-state.service';

const US_STATES: Array<{ code: string; name: string }> = [
  { code: 'AL', name: 'Alabama' }, { code: 'AK', name: 'Alaska' }, { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' }, { code: 'CA', name: 'California' }, { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' }, { code: 'DE', name: 'Delaware' }, { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' }, { code: 'HI', name: 'Hawaii' }, { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' }, { code: 'IN', name: 'Indiana' }, { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' }, { code: 'KY', name: 'Kentucky' }, { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' }, { code: 'MD', name: 'Maryland' }, { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' }, { code: 'MN', name: 'Minnesota' }, { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' }, { code: 'MT', name: 'Montana' }, { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' }, { code: 'NH', name: 'New Hampshire' }, { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' }, { code: 'NY', name: 'New York' }, { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' }, { code: 'OH', name: 'Ohio' }, { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' }, { code: 'PA', name: 'Pennsylvania' }, { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' }, { code: 'SD', name: 'South Dakota' }, { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' }, { code: 'UT', name: 'Utah' }, { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' }, { code: 'WA', name: 'Washington' }, { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' }, { code: 'WY', name: 'Wyoming' },
];

@Component({
  selector: 'app-welcome',
  standalone: true,
  imports: [CommonModule, FormsModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  styles: [`
    :host { display: block; }

    .hero {
      min-height: 100dvh;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 24px;
      position: relative;
      overflow: hidden;
      /* Deep navy base with a faded Statue of Liberty photo if present in
         assets/. The gradient sits on top so text stays readable even without
         the image. */
      background:
        linear-gradient(160deg, rgba(49,46,129,0.92) 0%, rgba(79,70,229,0.88) 55%, rgba(49,46,129,0.95) 100%),
        radial-gradient(circle at 80% 15%, rgba(129,140,248,0.35), transparent 45%),
        url('/assets/statue-of-liberty.jpg');
      background-size: cover;
      background-position: center;
    }

    .stars {
      position: absolute;
      inset: 0;
      background-image: radial-gradient(1.5px 1.5px at 20% 30%, rgba(255,255,255,0.35), transparent),
                        radial-gradient(1.5px 1.5px at 70% 60%, rgba(255,255,255,0.25), transparent),
                        radial-gradient(1.5px 1.5px at 40% 80%, rgba(255,255,255,0.2), transparent);
      pointer-events: none;
    }

    .card {
      position: relative;
      width: 100%;
      max-width: 400px;
      background: #ffffff;
      border-radius: 22px;
      padding: 32px 26px 28px;
      box-shadow: 0 24px 60px rgba(0,0,0,0.35);
    }

    .flag { font-size: 40px; text-align: center; margin-bottom: 8px; }

    h1 {
      font-size: 24px;
      font-weight: 800;
      color: #1e1b4b;
      text-align: center;
      letter-spacing: -0.02em;
      line-height: 1.25;
    }

    .subtitle {
      font-size: 14px;
      color: #6b7280;
      text-align: center;
      margin: 8px 0 24px;
      line-height: 1.5;
    }

    label {
      display: block;
      font-size: 12px;
      font-weight: 700;
      letter-spacing: 0.04em;
      text-transform: uppercase;
      color: #6366f1;
      margin-bottom: 6px;
    }

    .field { margin-bottom: 18px; }

    input, select {
      width: 100%;
      padding: 13px 14px;
      border-radius: 12px;
      border: 1.5px solid #e2e6f3;
      background: #f8f9ff;
      color: #1e1b4b;
      font-size: 15px;
      font-weight: 500;
      outline: none;
      transition: border-color 0.15s;
    }
    input:focus, select:focus { border-color: #4f46e5; }

    .cta {
      width: 100%;
      margin-top: 6px;
      padding: 15px;
      background: #4f46e5;
      color: #fff;
      border: none;
      border-radius: 12px;
      font-size: 15px;
      font-weight: 700;
      cursor: pointer;
      transition: background 0.15s, transform 0.1s, opacity 0.15s;
    }
    .cta:hover:not(:disabled) { background: #6366f1; }
    .cta:active:not(:disabled) { transform: scale(0.98); }
    .cta:disabled { opacity: 0.5; cursor: not-allowed; }

    .skip {
      display: block;
      width: 100%;
      margin-top: 12px;
      background: none;
      border: none;
      color: #9ca3af;
      font-size: 13px;
      font-weight: 600;
      cursor: pointer;
    }
    .skip:hover { color: #6b7280; }
  `],
  template: `
    <div class="hero">
      <div class="stars"></div>
      <div class="card">
        <div class="flag">🗽</div>
        <h1>Welcome to CitizenFlow</h1>
        <p class="subtitle">
          Your free, ad-free path to the U.S. Citizenship Test.
          Let's personalize your study.
        </p>

        <div class="field">
          <label for="firstName">First Name</label>
          <input
            id="firstName"
            type="text"
            [(ngModel)]="firstName"
            placeholder="e.g. Maria"
            autocomplete="given-name"
            (keyup.enter)="getStarted()"
            name="firstName"
          />
        </div>

        <div class="field">
          <label for="state">Your State</label>
          <select id="state" [(ngModel)]="homeState" name="homeState">
            @for (s of states; track s.code) {
              <option [value]="s.code">{{ s.name }}</option>
            }
          </select>
        </div>

        <button class="cta" [disabled]="!firstName.trim()" (click)="getStarted()">
          Get Started →
        </button>
        <button class="skip" (click)="skip()">Skip for now</button>
      </div>
    </div>
  `,
})
export class WelcomeComponent {
  private state = inject(AppStateService);
  private router = inject(Router);

  protected readonly states = US_STATES;

  firstName = '';
  homeState = 'WI';

  getStarted(): void {
    const name = this.firstName.trim();
    if (!name) return;
    this.state.setUserName(name);
    this.state.updateSettings({ homeState: this.homeState });
    this.router.navigate(['/']);
  }

  skip(): void {
    // Mark onboarding complete with the default name so we don't loop back here.
    this.state.setUserName('Future Citizen');
    this.router.navigate(['/']);
  }
}
