// CitizenshipApp/CitizenshipApp/app/history.tsx
import React from "react";
import {
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { router } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { ScreenBackground } from "@/components/ScreenBackground";
import { useApp } from "@/context/AppContext";

export default function HistoryScreen() {
  const { quizHistory, clearQuizHistory } = useApp();

  const passed = quizHistory.filter((h) => h.passed).length;
  const best = quizHistory.reduce(
    (m, h) => Math.max(m, Math.round((h.score / h.total) * 100)),
    0
  );

  function formatDate(iso: string): string {
    const d = new Date(iso);
    if (isNaN(d.getTime())) return iso;
    return d.toLocaleDateString("en-US", {
      month: "short", day: "numeric", year: "numeric",
      hour: "numeric", minute: "2-digit",
    });
  }

  function formatDuration(seconds: number): string {
    const m = Math.floor(seconds / 60);
    const s = seconds % 60;
    return `${m}:${s.toString().padStart(2, "0")}`;
  }

  return (
    <ScreenBackground>
      <SafeAreaView style={styles.root} edges={["top", "bottom"]}>
        <View style={styles.header}>
          <TouchableOpacity
            onPress={() => (router.canGoBack() ? router.back() : router.replace("/"))}
            hitSlop={12}
          >
            <Ionicons name="arrow-back" size={24} color="#4f46e5" />
          </TouchableOpacity>
          <Text style={styles.title}>Quiz History</Text>
          {quizHistory.length > 0 ? (
            <TouchableOpacity onPress={clearQuizHistory} hitSlop={10}>
              <Text style={styles.clear}>Clear</Text>
            </TouchableOpacity>
          ) : (
            <View style={{ width: 40 }} />
          )}
        </View>

        {quizHistory.length === 0 ? (
          <View style={styles.empty}>
            <Ionicons name="bar-chart-outline" size={64} color="#c7d2fe" />
            <Text style={styles.emptyText}>
              No quizzes yet. Take a practice test to start tracking your progress!
            </Text>
            <TouchableOpacity style={styles.emptyBtn} onPress={() => router.replace("/quiz")}>
              <Text style={styles.emptyBtnText}>Take a Quiz</Text>
            </TouchableOpacity>
          </View>
        ) : (
          <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
            <View style={styles.summary}>
              <Tile value={String(quizHistory.length)} label="Taken" color="#1a1f36" />
              <Tile value={String(passed)} label="Passed" color="#16a34a" />
              <Tile value={`${best}%`} label="Best" color="#4f46e5" />
            </View>

            {quizHistory.map((h, i) => {
              const pct = Math.round((h.score / h.total) * 100);
              return (
                <View
                  key={`${h.date}-${i}`}
                  style={[styles.row, { borderLeftColor: h.passed ? "#16a34a" : "#ef4444" }]}
                >
                  <View style={[styles.badge, { backgroundColor: h.passed ? "#dcfce7" : "#fee2e2" }]}>
                    <Text style={[styles.badgeText, { color: h.passed ? "#15803d" : "#b91c1c" }]}>
                      {pct}%
                    </Text>
                  </View>
                  <View style={styles.rowMain}>
                    <Text style={styles.rowScore}>
                      {h.score}/{h.total} correct ·{" "}
                      <Text style={{ color: h.passed ? "#16a34a" : "#ef4444" }}>
                        {h.passed ? "Passed" : "Failed"}
                      </Text>
                    </Text>
                    <Text style={styles.rowDate}>{formatDate(h.date)}</Text>
                  </View>
                  <Text style={styles.rowTime}>{formatDuration(h.durationSeconds)}</Text>
                </View>
              );
            })}
          </ScrollView>
        )}
      </SafeAreaView>
    </ScreenBackground>
  );
}

function Tile({ value, label, color }: { value: string; label: string; color: string }) {
  return (
    <View style={styles.tile}>
      <Text style={[styles.tileVal, { color }]}>{value}</Text>
      <Text style={styles.tileLbl}>{label}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 12,
  },
  title: { fontSize: 20, fontWeight: "800", color: "#1a1f36" },
  clear: { fontSize: 14, fontWeight: "600", color: "#ef4444" },
  scroll: { padding: 16, paddingBottom: 40, gap: 10 },
  summary: { flexDirection: "row", gap: 10, marginBottom: 8 },
  tile: {
    flex: 1, backgroundColor: "#fff", borderRadius: 12, padding: 14, alignItems: "center",
    shadowColor: "#000", shadowOpacity: 0.05, shadowRadius: 8, shadowOffset: { width: 0, height: 2 }, elevation: 3,
  },
  tileVal: { fontSize: 20, fontWeight: "700" },
  tileLbl: { fontSize: 10, fontWeight: "600", letterSpacing: 0.4, textTransform: "uppercase", color: "#9ca3af", marginTop: 4 },
  row: {
    flexDirection: "row", alignItems: "center", gap: 14,
    backgroundColor: "#fff", borderRadius: 12, padding: 14, borderLeftWidth: 4,
    shadowColor: "#000", shadowOpacity: 0.05, shadowRadius: 8, shadowOffset: { width: 0, height: 2 }, elevation: 2,
  },
  badge: { width: 46, height: 46, borderRadius: 12, alignItems: "center", justifyContent: "center" },
  badgeText: { fontSize: 14, fontWeight: "800" },
  rowMain: { flex: 1 },
  rowScore: { fontSize: 15, fontWeight: "700", color: "#1a1f36" },
  rowDate: { fontSize: 12, color: "#9ca3af", marginTop: 2 },
  rowTime: { fontSize: 12, color: "#6b7280", fontWeight: "600" },
  empty: { flex: 1, alignItems: "center", justifyContent: "center", padding: 32, gap: 16 },
  emptyText: { fontSize: 15, color: "#94a3b8", textAlign: "center", lineHeight: 22 },
  emptyBtn: { backgroundColor: "#4f46e5", borderRadius: 12, paddingVertical: 12, paddingHorizontal: 24 },
  emptyBtnText: { color: "#fff", fontWeight: "700", fontSize: 14 },
});

// Frontend/src/app/pages/history/history.component.ts
import { Component, inject, computed, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { AppStateService } from '../../services/app-state.service';

@Component({
  selector: 'app-history',
  standalone: true,
  imports: [CommonModule, RouterModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  styles: [`
    .page { padding: 20px 16px 80px; max-width: 480px; margin: 0 auto; }

    .header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-bottom: 16px;
    }
    h1 { font-size: 22px; font-weight: 700; color: #1e1b4b; letter-spacing: -0.02em; }
    .clear-btn {
      background: none; border: none; color: #ef4444;
      font-size: 13px; font-weight: 600; cursor: pointer;
    }

    /* ── Summary tiles ── */
    .summary {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 10px;
      margin-bottom: 20px;
    }
    .tile {
      background: #fff; border-radius: 12px; padding: 14px 12px; text-align: center;
      box-shadow: 0 2px 8px rgba(0,0,0,0.05);
    }
    .tile .val { font-size: 20px; font-weight: 700; color: #1e1b4b; }
    .tile .lbl { font-size: 10px; font-weight: 600; letter-spacing: 0.04em; text-transform: uppercase; color: #9ca3af; margin-top: 4px; }

    /* ── List ── */
    .list { display: flex; flex-direction: column; gap: 10px; }

    .row {
      display: flex;
      align-items: center;
      gap: 14px;
      background: #fff;
      border-radius: 12px;
      padding: 14px 16px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.05);
      border-left: 4px solid transparent;
    }
    .row.pass { border-left-color: #16a34a; }
    .row.fail { border-left-color: #ef4444; }

    .badge {
      width: 46px; height: 46px; border-radius: 12px;
      display: flex; align-items: center; justify-content: center;
      font-size: 15px; font-weight: 800; flex-shrink: 0;
    }
    .badge.pass { background: #dcfce7; color: #15803d; }
    .badge.fail { background: #fee2e2; color: #b91c1c; }

    .row-main { flex: 1; }
    .row-score { font-size: 15px; font-weight: 700; color: #1e1b4b; }
    .row-score .status-pass { color: #16a34a; }
    .row-score .status-fail { color: #ef4444; }
    .row-date { font-size: 12px; color: #9ca3af; margin-top: 2px; }
    .row-time { font-size: 12px; color: #6b7280; font-weight: 600; white-space: nowrap; }

    /* ── Empty ── */
    .empty { text-align: center; padding: 56px 24px; color: #9ca3af; }
    .empty .icon { font-size: 40px; margin-bottom: 12px; }
    .empty p { font-size: 14px; margin-bottom: 20px; }
    .empty a {
      display: inline-block; padding: 12px 22px; background: #4f46e5; color: #fff;
      border-radius: 10px; font-size: 14px; font-weight: 700; text-decoration: none;
    }
  `],
  template: `
    <div class="page">
      <div class="header">
        <h1>Quiz History</h1>
        @if (history().length > 0) {
          <button class="clear-btn" (click)="clear()">Clear</button>
        }
      </div>

      @if (history().length === 0) {
        <div class="empty">
          <div class="icon">📊</div>
          <p>No quizzes yet. Take your first practice test to start tracking your progress!</p>
          <a routerLink="/quiz">Take a Quiz</a>
        </div>
      } @else {
        <div class="summary">
          <div class="tile">
            <div class="val">{{ history().length }}</div>
            <div class="lbl">Taken</div>
          </div>
          <div class="tile">
            <div class="val" style="color:#16a34a">{{ passedCount() }}</div>
            <div class="lbl">Passed</div>
          </div>
          <div class="tile">
            <div class="val" style="color:#4f46e5">{{ bestPercent() }}%</div>
            <div class="lbl">Best</div>
          </div>
        </div>

        <div class="list">
          @for (h of history(); track h.date) {
            <div class="row" [class.pass]="h.isPassed" [class.fail]="!h.isPassed">
              <div class="badge" [class.pass]="h.isPassed" [class.fail]="!h.isPassed">
                {{ h.scorePercent }}%
              </div>
              <div class="row-main">
                <div class="row-score">
                  {{ h.correctCount }}/{{ h.totalQuestions }} correct ·
                  <span [class.status-pass]="h.isPassed" [class.status-fail]="!h.isPassed">
                    {{ h.isPassed ? 'Passed' : 'Failed' }}
                  </span>
                </div>
                <div class="row-date">{{ formatDate(h.date) }}</div>
              </div>
              <div class="row-time">{{ formatDuration(h.durationSeconds) }}</div>
            </div>
          }
        </div>
      }
    </div>
  `,
})
export class HistoryComponent {
  protected state = inject(AppStateService);

  history = this.state.quizHistory;

  passedCount = computed(() => this.history().filter(h => h.isPassed).length);
  bestPercent = computed(() =>
    this.history().reduce((max, h) => Math.max(max, h.scorePercent), 0)
  );

  clear(): void {
    this.state.clearQuizHistory();
  }

  formatDate(iso: string): string {
    const d = new Date(iso);
    if (isNaN(d.getTime())) return iso;
    return d.toLocaleDateString('en-US', {
      month: 'short', day: 'numeric', year: 'numeric',
      hour: 'numeric', minute: '2-digit',
    });
  }

  formatDuration(seconds: number): string {
    const m = Math.floor(seconds / 60);
    const s = seconds % 60;
    return `${m}:${s.toString().padStart(2, '0')}`;
  }
}
